### ISSUE TITLE
adding second optional parameter 

### ISSUE THREAD

**Issue by leostereo** [tonydm/smokeping-OpenSSHMikrotikRouterOSPing#2]
Dear tony.
Sorry ... its me again.
I will try to modify your pm module to accept a second optinal parameter.
I found very usefull to set the "routing-table" while ping.
This force router to send ping over not active default route.
For example to exec this:
`ping 8.8.8.8 routing-table=uen_itx`

so I will try:
line 86
`  my $rtable = $target->{vars}{rtable};`

and  line 122
```
  if($psource && $rtable){
    @output = $ssh->capture("ping $dest routing-table=$rtable count=$pings size=$bytes src-address=$psource");
  }elsif ( $rtable ) {
    @output = $ssh->capture("ping $dest routing-table=$rtable count=$pings size=$bytes");
  }elsif ( $psource ) {
    @output = $ssh->capture("ping $dest count=$pings size=$bytes src-address=$psource");
  } else {
    @output = $ssh->capture("ping $dest count=$pings size=$bytes");
  }
```

This definition does not work:

```
+ ROUTE_TEST
menu = ROUTE_TEST
probe = OpenSSHMikrotikRouterOSPing
title = google_x_itx
ssh_port = 22000
host = 8.8.8.8
source = 10.20.20.4
rtable = uen_itx
```
it yelds: unknown variable 'rtable'".
Can you help me ?

Regards.
Leandro.

**Comment by leostereo** [comment]
ok , it is working.
Just need to add rtable to param list in the params array.
Added at the end of the list like: 
```
    rtable => {
        _doc => 'choose routing table',
    },
```
Thanks.

**Comment by tonydm** [comment]
Hi leostereo,

Very interesting!  Glad you isolated the issue and code solution, great work!  Curious, the target host was not out the default route, obviously.  The default route would, of course, be used if there was no known route (dynamic, static, OSPF, EIGRP, etc) in your Mtik routing table.  Do you have two or more WAN facing upstream providers?  Or some other unique IP structure for your use case?  I had assumed that the target IP you had issue with was a public address and therefore would have been routed out your default 0.0.0.0/0 route.  I have used IP->Routes->Rules to direct traffic based on packet marking.  In my case it was having multiple upstream providers at different edge RTRs on the same physical network.  So I wanted certain IP/IP Blocks to use a given US provider.  This sounds like something that should be merged into the project.  Do you want to create a pull request with which I will merge?  Some additional documentation/explanation of the need to use will be helpful for others too.

~Tony

**Comment by leostereo** [comment]
Take a look at my routing situation:
```
[inet@R_BGP] > ip route print where dst-address=0.0.0.0/0
Flags: X - disabled, A - active, D - dynamic, C - connect, S - static, r - rip, b - 
bgp, o - ospf, m - mme, B - blackhole, U - unreachable, P - prohibit 
 #      DST-ADDRESS        PREF-SRC        GATEWAY            DISTANCE
 0 A S  0.0.0.0/0                         11.32.65.29            20
 1   S  0.0.0.0/0                          11.80.25.1               18
 2   S  0.0.0.0/0                          12.17.50.1             19
```
As you can see I have 3 upsream providers.
Only one active and 2 backups defautl gateways.
I would like to monitor latency to same internet services for all of them, so , in order to force ping to go for desired default gateway you can use the "route-table" command if previusly created a mark for this route.
As you mentioned,  you can craete a policy for every target but this would be very resource consuming for just a ping probe.
Regarding pull request.
sure, lets do.

**Comment by tonydm** [comment]
Makes perfect sense with the clarification if the multiple default gateways.  Do you want to create the Pull Request?  I'll verify it and Merge it.  Otherwise I'll just incorporate the needed changes to allow for specifying a routing table.

Best!

~Tony
