### ISSUE TITLE
multiplex_ssh collides

### ISSUE THREAD

**Issue by ctc** [tonydm/smokeping-OpenSSHMikrotikRouterOSPing#7]
Seems multiplex_ssh collides if there a many same hosts and threads.

OpenSSHMikrotikRouterOSPing: OpenSSHMikrotikRouterOSPing connecting 10.0.101.38: unable to establish master SSH connection: bad ssh master at /var/lib/smokeping/.libnet-openssh-perl/control-smokeping@10.0.101.38 socket owned by pid 318032 (pid 317986 expected)
OpenSSHMikrotikRouterOSPing: OpenSSHMikrotikRouterOSPing connecting 10.0.101.38: unable to establish master SSH connection: bad ssh master at /var/lib/smokeping/.libnet-openssh-perl/control-smokeping@10.0.101.38 socket owned by pid 318032 (pid 317980 expected)

**Comment by tonydm** [comment]
@ctc This would be an issue with [OpenSSH](https://www.openssh.com/) and not isolated to this module.  Closing

**Comment by tonydm** [comment]
@ctc 

You might take a look at [Bug #70561 for Net-OpenSSH: unable to establish master SSH connection: bad ssh master](https://rt.cpan.org/Public/Bug/Display.html?id=70561)

Stated possible solution:

>
>Try passing the full path to the ssh command in the constructor:
>
>  my $ssh = Net::OpenSSH->new(...,
>                                 ssh_cmd => '/usr/bin/ssh');


So in your Probes definition:
```
forks = 5
offset = 50%
packetsize = 56
step = 300
timeout = 60
pings = 20
routerosuser = <rosuser>
routerospass = <rospasswd>
...
ssh_binary_path = /usr/bin/ssh  <----- Specify the full path to the ssh binary
...

```
