### ISSUE TITLE
OpenSSH Error

### ISSUE THREAD

**Issue by MHammett** [tonydm/smokeping-OpenSSHMikrotikRouterOSPing#9]
Sep 28 13:47:05 Smokeping smokeping[36093]: Use of uninitialized value $call[3] in exec at /usr/local/share/perl/5.28.1/Net/OpenSSH.pm line 1014.
Sep 28 13:47:05 Smokeping smokeping[36091]: OpenSSHMikrotikRouterOSPing: OpenSSHMikrotikRouterOSPing connecting 208.89.144.11: unable to establish master SSH connection: bad password or master process exited unexpectedly

I did verify that the OpenSSH client was installed.

**Comment by tonydm** [comment]
Hello,

This is a common error usually associated with a path and/or permissions issue.  Verifying that OpenSSH client is installed is good step.  Please, kindly review the [Multiplexed SSH Connections](https://github.com/tonydm/smokeping-OpenSSHMikrotikRouterOSPing/tree/master#multiplexed-ssh-connections-1)  section of the README.  It describes why you see this error and how to properly set up the path and permissions for the Multiplexed Sessions Master Control Session files.  You will have to adapt the examples to your Smokeping installation method, user:group, etc.  Then please review the next section [Smokeping Config](https://github.com/tonydm/smokeping-OpenSSHMikrotikRouterOSPing/tree/master#smokeping-config).  It shows sample Probe and Target config file examples on how to configure Multiplex feature settings Enable/Disable, Control File Path, Persist time, Debug, Debug log file on the Probe itself and on a per Target basis.

**Comment by MHammett** [comment]
I saw that before your comment and couldn't make it work, so I turned on debugging.

I got this:
2023/09/28 16:11:15 7EB78B6927: Debugging enabled...
2023/09/28 16:11:15 7EB78B6927: Using OpenSSH ControlMaster Multiplex connections!
2023/09/28 16:11:15 7EB78B6927: Master Control Socket file: /tmp/smokeping_ssh_sockets/control-smokeping@[redacted]does not exist!  Creating new socket file.
2023/09/28 16:11:15 7EB78B6927: Net::OpenSSH->new options:
$VAR1 = {
          'ctl_path' => '/tmp/smokeping_ssh_sockets/control-smokeping@[redacted]',
          'ctl_dir' => '/tmp/smokeping_ssh_sockets',
          'timeout' => 60,
          'user' => '[redacting]',
          'password' => '[redacted]',
          'ssh_cmd' => '/usr/bin/ssh',
          'master_opts' => [
                             '-oStrictHostKeyChecking=no',
                             '-oControlPersist=10m',
                             undef
                           ],
          'strict_mode' => 0,
          'port' => 22
        };

Is the socket control pile persistent, or does it go away when the process closes?


BTW: There is some inconsistency in multiplex_control_file_path vs multiplex_control_socket_path in the documentation.

**Comment by MHammett** [comment]
I tried disabling multiplexing to see if I was getting any other errors, and now I'm getting an SSH error that I don't get when SSHing from the bash prompt.

Sep 28 16:16:19 Smokeping smokeping[13972]: OpenSSHMikrotikRouterOSPing: OpenSSHMikrotikRouterOSPing connecting [redacted]: unable to establish master SSH connection: the authenticity of the target host can't be established; the remote host public key is probably not present in the '~/.ssh/known_hosts' file


Do I need to load every remote host in that file? I ran SSH via sudo as the smokeping error and it went away, so maybe?

**Comment by tonydm** [comment]
Control file persistence depends on your installation method type and Smokeping set up.  If you installed Smokeping bare metal on the host then your SSH Control files will persist for as long as the host is up and within the multiplex_control_persist_time setting defined.  The value is in minutes.  If using Docker, as shown in my examples, then it will depend on if the Container's /tmp/smokeping_ssh_sockets directory is Bind Mount'd to the host and also depending on the multiplex_control_persist_time value defined.  If the container is stopped or restarted, the control file will persist on the host.  If the container does not have the control file path mounted to the host, then it will disappear when the container if restarted.  If only stopped and started, the container state will persist.

You don't need to configure every Target host.  The module will dynamically create the control file and use the Probe's defined values of the default values.

For security reasons StrictHostModeChecking is left enabled by default.  I haven't added this override to the options available.

SSH's known_host file needs to have the target host listed in the SSH users $HOME/.ssh/known_hosts file.  If it is not, regardless of your install, bare metal or dockerized, you must login to the host from the command line to accept the [yes/no] prompt and thereby add the entry to the known hosts file.  And again, depending on if you are bare metal or docker, the .ssh keys and known_hosts file persists accordingly.

Thank you for pointing out the documentation discrepancy.  I will correct that asap.

I hope this helps

**Comment by MHammett** [comment]
I'm not in Docker.

So that if I have no files in the directory, it likely is a permissions issue. I'll dig into that a bit more tomorrow and see what I can come up with.

**Comment by tonydm** [comment]
You've opened another issue indicating that this issue has been resolved.
